akaAgar/briefing-room-for-dcs

Source/Generator/MissionGeneratorEnemyFighterPatrols.cs
Source/Generator/MissionGeneratorPlayerFlightGroups.cs
Source/Template/MissionTemplate.cs

Playing with a friend we realised it would be nice to have AI supporting us.
Seems to work fine just loading and starting the mission up.

Move SP AI aircraft to be available in MP

---

Include/Lua/Script.lua
Source/Generator/MissionGenerator.cs
Source/Mission/DCSMission.cs
Source/Miz/MizMakerLuaScript.cs
Source/Template/MissionTemplate.cs

Pretty new to Lua but this did work in a quick test

add radio sound options

---

Database/Units/PlaneFighter/FA-18C Hornet.ini

fix default hornet loadout

---

Source/AmountN.cs
Source/BriefingRoom.csproj
Source/Generator/GeneratorTools.cs
Source/Generator/MissionGenerator.cs
Source/Generator/MissionGeneratorAirDefense.cs
Source/Generator/MissionGeneratorEnemyAirDefense.cs
Source/Generator/MissionGeneratorEnemyFighterPatrols.cs
Source/Generator/MissionGeneratorSupportUnits.cs
Source/Template/MissionTemplate.cs

Adds Random  to AmountN enum and function to get a random value 
Note: This is not a consistent random ie embedded objective and general air defence could be at different levels

Random defence

---

.gitignore
Database/Units/ShipCarrier/Admiral Kuznetsov carrier (2017).ini
Database/Units/ShipCarrier/USS Abraham Lincoln.ini
Database/Units/ShipCarrier/USS George Washington.ini
Database/Units/ShipCarrier/USS Harry S Truman.ini
Database/Units/ShipCarrier/USS Theodore Roosevelt.ini
Include/Briefing.html
Include/Lua/Units/GroupAircraftPlayerCarrier.lua
Include/Lua/Units/GroupCarrier.lua
Source/BriefingRoom.csproj
Source/DB/Database.cs
Source/Generator/MissionGenerator.cs
Source/Generator/MissionGeneratorAirbases.cs
Source/Generator/MissionGeneratorBriefing.cs
Source/Generator/MissionGeneratorCarrier.cs
Source/Generator/MissionGeneratorPlayerFlightGroups.cs
Source/Mission/DCSMission.cs
Source/Miz/MizMakerLuaMission.cs
Source/Template/MissionTemplate.cs
Source/Template/MissionTemplateMPFlightGroup.cs
Source/TypeConverters/DBEntryCarrierConverter.cs

I'm considering the various options for this out of scope for now

Simple Carrier Implementation

---

Database/Objectives/Deep strike.ini
Database/Units/StaticStructureProduction/Tank 2.ini
Database/Units/StaticStructureProduction/Tank 3.ini
Database/Units/StaticStructureProduction/Tank.ini
Include/Lua/Script.lua
Source/Generator/MissionGeneratorObjectivesUnitGroups.cs

Limitation static objects are single unit groups so only 1 target can be created at each location

initial static targets support

---

Source/Generator/MissionGeneratorBriefing.cs

had the UI briefing info wrong

fix bad briefing

---

Database/Units/PlaneFighter/F-5E Tiger II.ini

Remove tiger II from playable

---

Include/Lua/Units/UnitAircraft.lua
Source/Miz/MizMakerLuaMission.cs

correct aircraft spawn

---

Database/Units/PlaneFighter/F-14A-GR Tomcat.ini

Don't own the module so its just a F-14B with the ID changed,

Added F-14A-135-GR

---

Database/MissionFeatures/ObjectiveDestroyParkedAircraft.ini
Database/Objectives/Offensive Counter Air.ini
Include/Lua/IncludedScripts/ObjectiveDestroyParkedAircraft.lua
Include/Lua/Script.lua
Include/Lua/Units/GroupAircraftStatic.lua
Source/Generator/MissionGenerator.cs
Source/Generator/MissionGeneratorAirbases.cs
Source/Generator/MissionGeneratorObjectives.cs
Source/Generator/MissionGeneratorObjectivesUnitGroups.cs
Source/Mission/DCSMissionObjective.cs
Source/Miz/MizMakerLuaMission.cs
Source/TheaterSpawnPointType.cs

Description isn't great but its functional.
Requires "Mission Kill" to avoid having to destroy aircraft completely

OCA mission type

---

Include/Lua/Units/GroupCarrier.lua
Source/Coordinates.cs
Source/Generator/MissionGenerator.cs
Source/Generator/MissionGeneratorCarrier.cs
Source/Generator/MissionGeneratorWeather.cs
Source/Mission/DCSMissionUnitGroup.cs
Source/Miz/MizMakerLuaMission.cs
Source/Toolbox.cs

Min speed 5tks default 0 wind speed 25kts. Waypoint has a distance for approx 2 hours
Known issue: Waypoint can end up on land and if the ship is close to land then this may cause issues)
Fix: Open In editor and shift ship back (figure its easy enough)

Carrier has waypoints relative to wind

---

Database/Units/PlaneFighter/MiG-15bis Fagot.ini

https://en.wikipedia.org/wiki/Mikoyan-Gurevich_MiG-15#Former_operators

Update MiG-15bis Fagot.ini

---

Database/Units/PlaneDrone/RQ-1A Predator.ini

https://en.wikipedia.org/wiki/General_Atomics_MQ-1_Predator#Operators

Update RQ-1A Predator.ini

---

Database/Units/PlaneFighter/A-4C Skyhawk (MOD).ini
Database/Units/PlaneFighter/F-22A Raptor (MOD).ini

Not sure if `RequiredMod` actually does anything but covering it off anyway. If we don't wanna merge popular mod aircraft then this can be a config for those intrested.

Add F-22A and A-4C Mod aircraft

---

Include/Lua/Units/GroupAircraftTanker.lua
Source/Generator/MissionGeneratorSupportUnits.cs
Source/Tacan.cs

fixes #115 
X47 was a duplicate
AA Missing AA mode marker and AA mode frequency calculation too

correct tacan freqency and channel

---

Database/Units/HelicopterAttack/Ka-50 Hokum.ini
Database/Units/HelicopterAttack/SA342 Gazelle (minigun).ini
Database/Units/HelicopterAttack/SA342 Gazelle (mistral).ini
Database/Units/HelicopterAttack/SA342L Gazelle.ini
Database/Units/HelicopterAttack/SA342M Gazelle.ini
Database/Units/HelicopterTransport/Mi-8MT Hip.ini
Database/Units/HelicopterUtility/UH-1H Huey.ini
Database/Units/PlaneAttack/AV-8BNA Harrier.ini
Database/Units/PlaneAttack/C-101CC Aviojet.ini
Database/Units/PlaneFighter/AJS-37 Viggen.ini
Database/Units/PlaneFighter/F-14A-GR Tomcat.ini
Database/Units/PlaneFighter/F-14B Tomcat.ini
Database/Units/PlaneFighter/F-16C Fighting Falcon.ini
Database/Units/PlaneFighter/F-5E-3 Tiger II.ini
Database/Units/PlaneFighter/F-86F Sabre.ini
Database/Units/PlaneFighter/I-16 Ishak.ini
Database/Units/PlaneFighter/JF-17 Thunder.ini
Database/Units/PlaneFighter/Messerschmitt Bf 109K-4.ini
Database/Units/PlaneFighter/MiG-19P Farmer.ini
Database/Units/PlaneFighter/MiG-21bis Fishbed.ini
Database/Units/PlaneFighter/Mirage 2000C.ini
Database/Units/PlaneFighter/P-47D-30 Thunderbolt (bl. 1).ini
Database/Units/PlaneFighter/P-47D-30 Thunderbolt.ini
Database/Units/PlaneFighter/P-47D-40 Thunderbolt.ini
Database/Units/PlaneFighter/P-51D Mustang.ini
Database/Units/PlaneFighter/P-51D-30-NA Mustang.ini
Database/Units/PlaneFighter/Spitfire FL Mk IX CW.ini
Database/Units/PlaneFighter/Spitfire FL Mk IX.ini
Database/Units/_AircraftMods/A-4E-C Skyhawk (MOD).ini
Database/Units/_AircraftMods/F-22A Raptor (MOD).ini

setup playable aircraft base data

---

Database/Extensions/Map markers.ini
Database/Extensions/MapMarkers.ini
Include/Lua/IncludedScripts/ExtensionMarkWaypoints.lua
Source/Miz/MizMakerLuaScript.cs

#91 
This took me so long until I realised the XYZ is implemented the wrong way round.

add map markers as extension

---

Include/Lua/Units/GroupAircraftAWACSMortal.lua
Include/Lua/Units/GroupAircraftTankerMortal.lua
Source/Generator/MissionGenerator.cs
Source/Generator/MissionGeneratorEnemySupportUnits.cs
Source/Template/MissionTemplate.cs

add enemy support units

---

Include/Lua/Options.lua

enable Labels on Dedicate Servers

---

Database/Names.ini
Database/Objectives/AntishipStrike.ini
Database/Objectives/BattleDamageAssessment.ini
Database/Objectives/CloseAirSupport.ini
Database/Objectives/CombatSearchAndRescue.ini
Database/Objectives/CombatSearchAndRescue_AIHelicopter.disabled
Database/Objectives/DefensiveCounterAir.ini
Database/Objectives/OffensiveCounterAir.ini
Database/Objectives/OffensiveCounterAir_OpenParkingsOnly.ini
Database/Objectives/Patrol.ini

Here are a few spelling/grammar fixes for INI files in the database.
I suggest also renaming **bataillon** to **[battalion](https://en.wiktionary.org/wiki/battalion)** but I haven't made that change here.  I leave it to your discretion.

Fix spelling/grammar in database files

---

Database/Units/PlaneFighter/MiG-19P.ini

fix mig-19

---

Database/Units/ShipCarrier/CVN_71.ini
Database/Units/ShipCarrier/CVN_72.ini
Database/Units/ShipCarrier/CVN_73.ini
Database/Units/ShipCarrier/CVN_75.ini
Database/Units/ShipCarrier/CV_1143_5.ini
Database/Units/ShipCarrier/KUZNECOW.ini
Database/Units/ShipCarrier/LHA_Tarawa.ini
Database/Units/ShipCarrier/Stennis.ini
Database/Units/ShipCarrier/VINSON.ini
Source/Generator/MissionGeneratorCarrier.cs

Hopefully fixes #161 by spawning ships in realistic formations as fleets not just a random splodge of ships
also re-implemented #124 as it got lost somehow.

Carrier formations

---

Database/Units/PlaneAttack/L-39C.ini
Database/Units/PlaneAttack/L-39ZA.ini
Database/Units/PlaneFighter/FW-190A8.ini
Database/Units/PlaneFighter/FW-190D9.ini

add new jets (Holding pattern for standalone library)

---

Database/Units/ShipCarrier/CVN_71.ini
Database/Units/ShipCarrier/CVN_72.ini
Database/Units/ShipCarrier/CVN_73.ini
Database/Units/ShipCarrier/CVN_75.ini
Database/Units/ShipCarrier/CV_1143_5.ini
Database/Units/ShipCarrier/KUZNECOW.ini
Database/Units/ShipCarrier/LHA_Tarawa.ini
Database/Units/ShipCarrier/Stennis.ini
Database/Units/ShipCarrier/VINSON.ini
Source/BriefingRoom/Generator/MissionGeneratorCarrierGroup.cs
Source/BriefingRoom/Generator/UnitMaker.cs

Spawns carriers and pre-built formations
Note TODO: Fix odd issue with Handy ending up in front of carrier if facing south

add carrier formations

---

Include/Lua/Units/UnitAircraft.lua
Include/Lua/Units/UnitShip.lua
Include/Lua/Units/UnitStatic.lua
Include/Lua/Units/UnitVehicle.lua
Source/BriefingRoom/Generator/UnitMaker.cs

Also Fixes issue with Additional units not spawning.
Makes code much easier to read and debug

breakdown AddUnitGroup and fix issues

---

Source/BriefingRoom/Generator/UnitMaker.cs
Source/BriefingRoom/Library/Coordinates.cs

Not completely working yet but better than before

Group Orientation

---

Database/Units/ShipCarrier/CVN_71.ini
Database/Units/ShipCarrier/CVN_72.ini
Database/Units/ShipCarrier/CVN_73.ini
Database/Units/ShipCarrier/CVN_75.ini
Database/Units/ShipCarrier/CV_1143_5.ini
Database/Units/ShipCarrier/KUZNECOW.ini
Database/Units/ShipCarrier/LHA_Tarawa.ini
Database/Units/ShipCarrier/Stennis.ini
Database/Units/ShipCarrier/VINSON.ini
Source/BriefingRoom/Generator/UnitMaker.cs
Source/BriefingRoom/Library/Coordinates.cs
Source/BriefingRoomGUI/Startup.cs

It seems I have it working its makes no sense but it works.

Orientation improvement

---

Source/BriefingRoom/Library/INIFile.cs
Source/BriefingRoom/Template/MissionTemplate.cs
Source/BriefingRoomCommonGUI/Pages/FullBuilder.razor
Source/BriefingRoomCommonGUI/Pages/QuickBuilder.razor
Source/BriefingRoomCommonGUI/Shared/NavMenu.razor
Source/BriefingRoomCommonGUI/wwwroot/css/site.css
Source/BriefingRoomCommonGUI/wwwroot/js/download.js

Implement new and better template loading

---

Database/DefaultUnitLists/FirstWorld.ini
Database/DefaultUnitLists/NonStateActors.ini
Database/DefaultUnitLists/SecondWorld.ini
Database/DefaultUnitLists/ThirdWorld.ini
Database/Names.ini
Database/Units/ShipCarrier/FOB.ini
Include/Lua/Units/UnitStaticFOB.lua
Source/BriefingRoom/Generator/MissionGenerator.cs
Source/BriefingRoom/Generator/MissionGeneratorCarrierGroup.cs
Source/BriefingRoom/Generator/MissionGeneratorPlayerFlightGroups.cs
Source/BriefingRoom/Library/Enums/UnitFamily.cs
Source/BriefingRoom/Library/Toolbox.cs

implement FOB as carrier

---

Database/MissionFeatures/SupportFriendlyBomber.ini
Database/MissionFeatures/SupportFriendlyCAP.ini
Database/MissionFeatures/SupportFriendlyCAS.ini
Database/MissionFeatures/SupportFriendlySEAD.ini
Include/Lua/MissionFeatures/SupportFriendlyBomber.lua
Include/Lua/MissionFeatures/SupportFriendlyCAP.lua
Include/Lua/MissionFeatures/SupportFriendlyCAS.lua
Include/Lua/MissionFeatures/SupportFriendlySEAD.lua
Include/Lua/Units/GroupAircraftOrbitingSEAD.lua
Source/BriefingRoom/Data/Entries/DBEntryFeature.cs
Source/BriefingRoom/Data/Enums/MissionFeatureUnitGroupFlags.cs
Source/BriefingRoom/Generator/MissionGeneratorFeatures.cs
Source/BriefingRoom/Generator/MissionGeneratorFeaturesMission.cs
Source/BriefingRoom/Generator/UnitMaker.cs
Source/BriefingRoom/Generator/UnitMakerGroupFlags.cs

Radio messages sound wise haven't been generated

Taskable Aircraft

---

.github/workflows/dotnet.yml
Source/BriefingRoom/BriefingRoom.csproj
Source/BriefingRoomCommandLine/BriefingRoomCommandLine.csproj
Source/BriefingRoomCommonGUI/BriefingRoomCommonGUI.csproj
Source/BriefingRoomDesktop/BriefingRoomDesktop.csproj
Source/BriefingRoomWeb/BriefingRoomWeb.csproj
Source/WkHtmlWrapper/WkHtmlWrapper.Core/WkHtmlWrapper.Core.csproj
Source/WkHtmlWrapper/WkHtmlWrapper.Image/WkHtmlWrapper.Image.csproj

Reverts akaAgar/briefing-room-for-dcs#562

Revert "Updated: Core to dotnet7"

---

Database/Language/UI.ini
Source/BriefingRoom/Campaign/CampaignGenerator.cs
Source/BriefingRoom/Generator/MissionGenerator.cs
Source/BriefingRoom/Generator/MissionGeneratorObjectives.cs
Source/BriefingRoom/Library/INIFile.cs
Source/BriefingRoom/Template/MissionTemplate.cs
Source/BriefingRoom/Template/MissionTemplateObjective.cs
Source/BriefingRoom/Template/Records/MissionTemplateObjectiveRecord.cs
Source/BriefingRoom/Template/Records/MissionTemplateRecord.cs
Source/BriefingRoomCommonGUI/Pages/FullBuilder.razor
Source/BriefingRoomCommonGUI/wwwroot/css/dark-mode.css
Source/BriefingRoomCommonGUI/wwwroot/js/map.js
Source/BriefingRoomDesktop/wwwroot/index.html
Source/BriefingRoomWeb/Pages/_Host.cshtml

Added: hint per objective

---

.github/workflows/dotnet.yml
Source/BriefingRoom/BriefingRoom.csproj
Source/BriefingRoomCommandLine/BriefingRoomCommandLine.csproj
Source/BriefingRoomCommonGUI/BriefingRoomCommonGUI.csproj
Source/BriefingRoomDesktop/BriefingRoomDesktop.csproj
Source/BriefingRoomWeb/BriefingRoomWeb.csproj
Source/WkHtmlWrapper/WkHtmlWrapper.Core/WkHtmlWrapper.Core.csproj
Source/WkHtmlWrapper/WkHtmlWrapper.Image/WkHtmlWrapper.Image.csproj

Reverts akaAgar/briefing-room-for-dcs#565

Updated: Core to dotnet7

---

Source/BriefingRoom/BriefingRoom.csproj

This reverts commit 5291223e849710b39fea33c2684ed814000f91ea.

Revert "Upgrade: Bump IronPdf from 2023.6.10 to 2023.9.8 in /Source"

---

Database/Language/de.ini
Include/Markdown/Manuals/Modder_Manual.md
Include/Markdown/Manuals/Translations_Manual.md
Source/BriefingRoom/Data/Common/DBCommon.cs
Source/BriefingRoom/Data/Common/DBCommonBriefing.cs
Source/BriefingRoom/Data/Common/DBCommonNames.cs
Source/BriefingRoom/Data/Database.cs
Source/BriefingRoom/Data/Entries/DBEntry.cs
Source/BriefingRoom/Data/Entries/DBEntryBriefingDescription.cs
Source/BriefingRoom/Data/Entries/DBEntryFeature.cs
Source/BriefingRoom/Data/Entries/DBEntryObjectiveTarget.cs
Source/BriefingRoom/Data/Entries/DBEntryObjectiveTask.cs
Source/BriefingRoom/Data/Entries/DBEntryWeatherPreset.cs
Source/BriefingRoom/Data/JSON/DBEntryAirbase.cs
Source/BriefingRoom/Data/JSON/DBEntryAircraft.cs
Source/BriefingRoom/Data/JSON/DBEntryCar.cs
Source/BriefingRoom/Data/JSON/DBEntryCargo.cs
Source/BriefingRoom/Data/JSON/DBEntryLayout.cs
Source/BriefingRoom/Data/JSON/DBEntryShip.cs
Source/BriefingRoom/Data/JSON/DBEntrySituation.cs
Source/BriefingRoom/Data/JSON/DBEntryStatic.cs
Source/BriefingRoom/Data/JSON/DBEntryTemplate.cs
Source/BriefingRoom/Library/INIFile.cs
Source/BriefingRoom/Library/LanguageString.cs
Source/BriefingRoomCommonGUI/Pages/CampaignBuilder.razor
Source/BriefingRoomCommonGUI/Pages/FullBuilder.razor
Source/BriefingRoomCommonGUI/Pages/QuickBuilder.razor
Source/BriefingRoomCommonGUI/Utils/BuilderUtils.cs

Implement Translate Overrides

---

Include/Lua/Script.lua

Common kill event basics
